feat: add optional automatic release notes generation
This commit introduces an optional feature for automatic generation of
release notes. This feature is commented out by default and can be
enabled by uncommenting the relevant lines in the
release-pypi-package.yaml.j2 file.

The feature uses the llamabot tool to generate release notes and the
pre-commit tool to ensure that all generated files adhere to the file
quality standards.

Note: This feature requires an OpenAI API key. Please consult the
llamabot CLI documentation for more information.

diff --git a/pyds/cli/templates/.github/workflows/release-pypi-package.yaml.j2 b/pyds/cli/templates/.github/workflows/release-pypi-package.yaml.j2
--- a/pyds/cli/templates/.github/workflows/release-pypi-package.yaml.j2
+++ b/pyds/cli/templates/.github/workflows/release-pypi-package.yaml.j2
@@ -67,6 +67,26 @@ jobs:
       - name: Ensure tag creation
         run: git tag | grep ${{ env.version_number }}
 
+      # Uncomment the following if you want to have automatic release notes.
+      #
+      # NOTE: the line `pre-commit run --all-files || true` ensures that all LLM-generated files
+      # adhere to the file quality standards enforced in the pre-commit hooks.
+      # The `|| true` ensures that we get a `0` exit code even if the generated files do not pass checks,
+      # as the default configuration of pre-commit by this tool will automatically fix those files.
+      # NOTE: you will need an OpenAI API key.
+      # consult the `llamabot` CLI documentation for more information.
+      # https://ericmjl.github.io/llamabot/cli/llamabot/
+      # - name: Write release notes
+      #   run: |
+      #     python -m pip install -e .
+      #     python -m pip install -U llamabot pre-commit
+      #     llamabot configure api-key --api-key="${{ secrets.OPENAI_API_KEY }}"
+      #     llamabot configure default-model --model-name="${{ secrets.OPENAI_DEFAULT_MODEL }}"
+      #     llamabot git write-release-notes
+      #     pre-commit run --all-files || true
+      #     git add .
+      #     git commit -m "Add release notes for ${{ env.version_number }}"
+
       - name: Build package
         run: |
           python -m pip install build wheel
